baseURL = "https://owaspsamm.org/"
languageCode = "en-us"
title = "OWASP SAMM"
contentDir = "../../Current Releases/"
theme = "owasp-samm"
[params]
  ghrepo = "https://github.com/OWASP/samm/"
  ghraw = "https://raw.githubusercontent.com/OWASP/samm/"
  ghcontent = "Current Releases/"
[taxonomies]
  business_function = "business_functions"

[menu]
# Main menu
[[menu.main]]
    name = "Open Security Summit 2019"
    identifier = "Summit 2019"
    pre = ""
    weight = 1
    url = "/summit2019"
[[menu.main]]
    name = "v1.5"
    identifier = "v1.5"
    pre = ""
    weight = 10
    url = "/v1-5/downloads/"
[[menu.main]]
    name = "v2.0 Beta"
    identifier = "v2.0b"
    pre = ""
    weight = 20
    url = "/v2.0b/introduction/"
[[menu.main]]
    name = "Sponsors"
    identifier = "sponsors"
    pre = ""
    weight = 30
    url = "/sponsors"
[[menu.main]]
    name = "Events"
    identifier = "events"
    pre = ""
    weight = 5
    url = "/events"

